name: pydata-pandas-workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh=1.2.0
  - dask=0.18.1
  - fastparquet=0.1.5
  - ipykernel=5.1.1
  - ipython=7.6.0
  - ipywidgets=7.5.0
  - jupyterlab=0.35.5
  - nbconvert=5.5.0
  - nbdime=1.0.6
  - nbformat=4.4.0
  - nodejs=10.13.0
  - pandas=0.24.2
  - python=3.6.8
  - requests=2.22.0
  - pip:
    - barnum==0.5.1
    - parquet==1.2
    - pip>=18.0
    - python-snappy==0.5.3
    - thriftpy==0.3.9
    - urllib3==1.25.3
