name: pydata-pandas-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - jupyterlab
  - xlrd
  - xlsxwriter
  - dask
  - seaborn
  - pyarrow
  - fastparquet
  - bokeh
  - nbdime
  - nbformat
  - nodejs
  - python>=3.6.8
